# Generated by Django 3.2.6 on 2021-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('Tutorial', 'Tutorial'), ('Movie', 'Movie'), ('Music', 'Music'), ('Audio Book', 'Audio Book')], default='Tutorial', max_length=25),
            preserve_default=False,
        ),
    ]
