# Generated by Django 3.2.6 on 2021-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("content", "0003_auto_20210905_0854"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
        migrations.RemoveField(
            model_name="content",
            name="tag",
        ),
        migrations.AddField(
            model_name="content",
            name="tags",
            field=models.ManyToManyField(to="content.Tags"),
        ),
    ]
