# Generated by Django 3.2.6 on 2021-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("content", "0005_auto_20210905_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="tags",
            field=models.ManyToManyField(null=True, to="content.Tags"),
        ),
    ]
