# Generated by Django 3.2.6 on 2021-09-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='link',
            new_name='file',
        ),
    ]
