# Generated by Django 3.2.6 on 2021-09-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210905_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
