# Generated by Django 3.2.6 on 2021-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210905_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='preview',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
