# Generated by Django 3.2.6 on 2021-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210907_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='upload',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
