# Generated by Django 3.2.6 on 2021-09-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
