# Generated by Django 3.2.6 on 2021-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='preview',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
