# Generated by Django 3.2.6 on 2021-09-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210907_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
