# Generated by Django 3.2.6 on 2021-09-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210908_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Content',
            new_name='content',
        ),
    ]
